// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCggZXtaNWrnNTw-VGA5vVSnGKu9sKu_Fc',
    appId: '1:820921689871:web:9b063b74f9e6792f64807a',
    messagingSenderId: '820921689871',
    projectId: 'crud-operation-5d058',
    authDomain: 'crud-operation-5d058.firebaseapp.com',
    storageBucket: 'crud-operation-5d058.firebasestorage.app',
    measurementId: 'G-WFLEX7ZCC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu-AhHRZbB9nN2MODVeBf4BhVTvIzbwjk',
    appId: '1:820921689871:android:cc943a1eb500412964807a',
    messagingSenderId: '820921689871',
    projectId: 'crud-operation-5d058',
    storageBucket: 'crud-operation-5d058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4SXv4hf8yAnIsYSMsa0SRmJ-f87xaNik',
    appId: '1:820921689871:ios:ed2554c3a48cad4c64807a',
    messagingSenderId: '820921689871',
    projectId: 'crud-operation-5d058',
    storageBucket: 'crud-operation-5d058.firebasestorage.app',
    iosBundleId: 'com.example.crudOperation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCggZXtaNWrnNTw-VGA5vVSnGKu9sKu_Fc',
    appId: '1:820921689871:web:f874880456c2b3e664807a',
    messagingSenderId: '820921689871',
    projectId: 'crud-operation-5d058',
    authDomain: 'crud-operation-5d058.firebaseapp.com',
    storageBucket: 'crud-operation-5d058.firebasestorage.app',
    measurementId: 'G-CP54DVQ3VH',
  );
}
